### ISSUE TITLE
Fail to load file with non-latin letters in path.

### ISSUE THREAD

**Issue by funbiscuit** [dtschump/CImg#118]
I tried to open with CImg file with nonlatin letters (in my case it was "график.png") and CImg gave this error:

CImg Error: [instance(0,0,0,0,00000000,non-shared)] CImg<unsigned char>::load(): Failed to recognize format of file 'path-to-file'.

I found out that if in function
inline std::FILE *fopen(const char *const path, const char *const mode)

I change default way of opening file:
res = std_fopen(path,mode);
to another one:
fopen_s(&res, path, mode);

then my file will open without errors. It is in line 6147 in current master branch.
But I'm not sure if this is a correct way of solving a problem - that's why I post this as an issue.

**Comment by dtschump** [comment]
That's interesting, thanks for the notification.
Not sure what to do at this state, I will investigate.

**Comment by dtschump** [comment]
Does this commit https://github.com/dtschump/CImg/commit/a24658c7c7d3462ab806c36176a00556aea24a2f fix the issue ?

**Comment by funbiscuit** [comment]
With this commit it doesn't even compile. I use Win10 x64, Visual Studio 2015

It gives this error:

```
1>***\cimg.h(15164): error C4308: negative integral constant converted to unsigned type
1>  ***\cimg.h(15160): note: while compiling class template member function 'cimg_library::CImg<float>::_cimg_math_parser::_cimg_math_parser(const char *const ,const char *const ,const cimg_library::CImg<float> &,cimg_library::CImg<float> *const ,const cimg_library::CImgList<T> *const ,cimg_library::CImgList<T> *const ,const bool)'
1>          with
1>          [
1>              T=float
1>          ]
1>  ***\cimg.h(24047): note: see reference to function template instantiation 'cimg_library::CImg<float>::_cimg_math_parser::_cimg_math_parser(const char *const ,const char *const ,const cimg_library::CImg<float> &,cimg_library::CImg<float> *const ,const cimg_library::CImgList<T> *const ,cimg_library::CImgList<T> *const ,const bool)' being compiled
1>          with
1>          [
1>              T=float
1>          ]
1>  ***\cimg.h(24049): note: see reference to class template instantiation 'cimg_library::CImg<float>::_cimg_math_parser' being compiled
1>  ***\cimg.h(24038): note: while compiling class template member function 'double cimg_library::CImg<float>::_eval(cimg_library::CImg<float> *const ,const char *const ,const double,const double,const double,const double,const cimg_library::CImgList<T> *const ,cimg_library::CImgList<T> *const ) const'
1>          with
1>          [
1>              T=float
1>          ]
1>  ***\cimg.h(24033): note: see reference to function template instantiation 'double cimg_library::CImg<float>::_eval(cimg_library::CImg<float> *const ,const char *const ,const double,const double,const double,const double,const cimg_library::CImgList<T> *const ,cimg_library::CImgList<T> *const ) const' being compiled
1>          with
1>          [
1>              T=float
1>          ]
1>  ***\cimg.h(36186): note: see reference to class template instantiation 'cimg_library::CImg<float>' being compiled
1>  ***\cimg.h(58969): note: see reference to class template instantiation 'cimg_library::CImg<wchar_t>' being compiled
1>***\cimg.h(15164): warning C4307: '*': integral constant overflow
```

**Comment by dtschump** [comment]
OK, thanks, I've fixed this bug with commit https://github.com/dtschump/CImg/commit/2a0b755d65c0b46deac4adc9ae3a732a5b8e2e93 .
Could you try again please ?

**Comment by funbiscuit** [comment]
Yes, now it compiles. But still the same error when I open file with non latin letters:

CImg Error: [instance(0,0,0,0,00000000,non-shared)] CImg<unsigned char>::load(): Failed to open file 'path-to-file'.

But as before, if in function
inline std::FILE *fopen(const char *const path, const char *const mode)

I change default way of opening file:
res = std_fopen(path,mode);
to another one:
fopen_s(&res, path, mode);

Then it opens correctly.

**Comment by dtschump** [comment]
OK thanks for your tests.
The problem I have is that on Windows, the macro `std_fopen` is intended to be equal to `cimg::win_fopen()`, which is already a function that is intended to manage widechar characters in filenames. So this should already work out-of-the-box.

Does it work, if you replace line `58980` the call to `_wfopen()` by `_wfopen_s()` ?
I'd really like to understand what is going on.

**Comment by dtschump** [comment]
OK, I've committed the necessary changes : https://github.com/dtschump/CImg/commit/d72386a88de659d54649cfbda178f2d8da037a18
Could you try and tell me if that fixes your issue ?
Otherwise, could you send one example of a file that causes the error ?
Thanks!

**Comment by funbiscuit** [comment]
I replaced original return with this:


	std::FILE *file;

	_wfopen_s(&file, wpath, wmode);

	return file;

But still the same error.

Replacing
_wfopen_s(&file, wpath, wmode);

by
fopen_s(&file, path, mode);

makes it work. Maybe my char array is not what is expected by CImg.
I found postion of char array in memory and is not using ut8 or widechar, it is in windows-1251 encoding.

**Comment by dtschump** [comment]
> I found postion of char array in memory and is not using ut8 or widechar, it is in windows-1251 encoding.

Ahh, that is probably the problem then.
I'm not sure how to fix this. If I replace `wfopen()` by `fopen_s()`, then all files with UTF-8 filenames won't probably work anymore.

**Comment by funbiscuit** [comment]
Yeah, I understand that. I guess for the time being I'll be manually replacing it with fopen_s() until I convert my file opening dialog to something that returns utf8 string.
