### ISSUE TITLE
new warnings under gcc 8.0

### ISSUE THREAD

**Issue by dahtah** [dtschump/CImg#199]
Hi David, 

New warnings appear under gcc 8.0 (CRAN automatically tests imager under a variety of compilers, and the maintainers will grumble until we get this fixed). Not sure how significant the issues really are: 
```
  ../inst/include/CImg.h:55774:32: warning: 'void* memcpy(void*, const void*, size_t)' writing to an object of type 'struct cimg_library::CImg<char>' with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
  ../inst/include/CImg.h:55775:44: warning: 'void* memcpy(void*, const void*, size_t)' writing to an object of type 'struct cimg_library::CImg<char>' with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
  ../inst/include/CImg.h:55788:22: warning: 'void* memset(void*, int, size_t)' clearing an object of type 'struct cimg_library::CImg<char>' with no trivial copy-assignment; use assignment or value-initialization instead [-Wclass-memaccess]
  ../inst/include/CImg.h:55792:45: warning: 'void* memmove(void*, const void*, size_t)' writing to an object of type 'struct cimg_library::CImg<char>' with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
  ../inst/include/CImg.h:58819:20: warning: 'void* memset(void*, int, size_t)' clearing an object of type 'struct cimg_library::CImgList<unsigned char>' with no trivial copy-assignment; use assignment or value-initialization instead [-Wclass-memaccess]
```

**Comment by dtschump** [comment]
Hi Simon,
does they happen with the current version in the git repo ?
I've fixed similar warnings with g++8.0 last week, one of my colleague reported those.
Maybe I forgot some of them ?

**Comment by dahtah** [comment]
No, it's an earlier version. Probably fixed already, then. Haven't got GCC 8.0 here, I'm basing this on automated tests ran on a CRAN machine. Will report back if issues still arise, thanks!

**Comment by dahtah** [comment]
Hi David. Unfortunately, we're still seeing warnings: 

```
  ../inst/include/CImg.h:4854:21: warning: 'char* strncpy(char*, const char*, size_t)' output truncated before terminating nul copying as many bytes from a string as its length [-Wstringop-truncation]
 ../inst/include/CImg.h:55774:32: warning: 'void* memcpy(void*, const void*, size_t)' writing to an object of type 'struct cimg_library::CImg<char>' with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
  ../inst/include/CImg.h:55775:44: warning: 'void* memcpy(void*, const void*, size_t)' writing to an object of type 'struct cimg_library::CImg<char>' with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
  ../inst/include/CImg.h:55788:22: warning: 'void* memset(void*, int, size_t)' clearing an object of type 'struct cimg_library::CImg<char>' with no trivial copy-assignment; use assignment or value-initialization instead [-Wclass-memaccess]
  ../inst/include/CImg.h:55792:45: warning: 'void* memmove(void*, const void*, size_t)' writing to an object of type 'struct cimg_library::CImg<char>' with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
  ../inst/include/CImg.h:58819:20: warning: 'void* memset(void*, int, size_t)' clearing an object of type 'struct cimg_library::CImgList<unsigned char>' with no trivial copy-assignment; use assignment or value-initialization instead [-Wclass-memaccess]
 ../inst/include/CImg.h:55927:42: warning: 'void* memmove(void*, const void*, size_t)' writing to an object of type 'struct cimg_library::CImg<char>' with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
  ../inst/include/CImg.h:55928:22: warning: 'void* memset(void*, int, size_t)' clearing an object of type 'struct cimg_library::CImg<char>' with no trivial copy-assignment; use assignment or value-initialization instead [-Wclass-memaccess]
  ../inst/include/CImg.h:55933:33: warning: 'void* memcpy(void*, const void*, size_t)' writing to an object of type 'struct cimg_library::CImg<char>' with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
  ../inst/include/CImg.h:55934:41: warning: 'void* memcpy(void*, const void*, size_t)' writing to an object of type 'struct cimg_library::CImg<char>' with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
  ../inst/include/CImg.h:55935:52: warning: 'void* memset(void*, int, size_t)' clearing an object of type 'struct cimg_library::CImg<char>' with no trivial copy-assignment; use assignment or value-initialization instead [-Wclass-memaccess]
  ../inst/include/CImg.h:55936:22: warning: 'void* memset(void*, int, size_t)' clearing an object of type 'struct cimg_library::CImg<char>' with no trivial copy-assignment; use assignment or value-initialization instead [-Wclass-memaccess]
```

Complete list [here](https://www.stats.ox.ac.uk/pub/bdr/gcc8/imager.out)

**Comment by dtschump** [comment]
Hi Simon, this is strange, the line numbers do not correspond to actual code in current version of CImg.h. Are you sure you used the very latest version of the file ?

**Comment by dahtah** [comment]
Crap - no, my bad, I've mixed things up, it's still cimg_version 200. Don't know what happened there. Closing this for now, sorry.
